name: Build Data JSON

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Convert data.yml to data.json
        run: |
          npm install
          npm install -g yamljs
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
